<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutDir>$(SolutionDir).Build\Output\$(Platform)$(Configuration)\</OutDir>
    <IntermediateOutputPath>$(SolutionDir).Build\Intermediate\$(Platform)$(Configuration)\$(ProjectName)\</IntermediateOutputPath>
    <MSBuildLogFilePath>$(SolutionDir).Build\Logs\$(MSBuildProjectName)-$(Configuration)-$(Platform).log</MSBuildLogFilePath><LanguageStandard>stdcpp20</LanguageStandard>
    <LangVersion>stdcpp20</LangVersion>
    <WarningLevel>4</WarningLevel>
    <EnableWarningsAsErrors>true</EnableWarningsAsErrors>
  </PropertyGroup>
    <ItemDefinitionGroup>
      <ClCompile>
        <!-- Set the C++ language standard to C++20 -->
        <LanguageStandard>stdcpp20</LanguageStandard>

        <!-- Enable C++ warning level 4 -->
        <WarningLevel>Level4</WarningLevel>

        <!-- Treat all warnings as errors -->
        <TreatWarningAsError>true</TreatWarningAsError>
      </ClCompile>
  </ItemDefinitionGroup>
</Project>
